### ISSUE TITLE
Candidate with single Context

### ISSUE THREAD

**Issue by AaronDeRybelHowest** [HazyResearch/snorkel#1039]
Hi I'm new to snorkel and i've read up on all the toturials and slides.
I'm impressed and excited about the potential, So i've set up a simple project.

This is what i'm trying to achieve:
Making labels for the url address of phishing/non-phishing websites.

I Already have some nice datasets with golden labels.

My plan of approach:
Feeding the entire url to the candidate object.
checking entire url for specific strings using simple regex. (domain knowledge)

As of now I don't see how it is possible to feed Candidate single context objects.
would it look like this ?  : candidate_subclass('Url' , ['url']). 

It seems that this is not supported, referring to : 
https://github.com/HazyResearch/snorkel/issues/755

Maybe you can provide explanations, examples for this situation ?

Many thanks!

**Comment by ajratner** [comment]
Hi @AaronDeRybelHowest sounds like a cool use case!  This should be covered, and for an example check out the [Crowdsourcing tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/crowdsourcing/Crowdsourced_Sentiment_Analysis.ipynb) (not because it needs to be crowdsourcing-labeled, just because this tutorial happens to do classification over single blogs of text as in your case).  I think this should work- if not feel free to re-open this issue!

**Comment by vumaasha** [comment]
Thanks for this example. IMHO this example should be in the intro section, a plain simple classification. It took me couple of days to land here after fiddling around with the current introduction section on finding spouse mentions
