### ISSUE TITLE
Fitting generative model to custom Data

### ISSUE THREAD

**Issue by highflyingbird-ust** [HazyResearch/snorkel#1058]
I understand snorkel was designed for relation extraction problems. But the concept of generating probabilistic functions over noisy signals can be used for a lot of labeling problems. Is there a way we can train the generative model without converting the data into candidate objects?

**Comment by bhancock8** [comment]
Yes! The easiest way to do that would be to use the Snorkel MeTaL repository: https://github.com/HazyResearch/metal. The "sample usage" on the main repo README should show you how to do what you want (or look at the Basic.ipynb tutorial). Basically the `LabelModel` object takes in a matrix of noisy labels and outputs probabilistic labels. And it does it with a new formulation of data programming using a matrix completion approach (rather than gibbs sampling) which is much faster.
