### ISSUE TITLE
Why does we call it marginals function?

### ISSUE THREAD

**Issue by rtygbwwwerr** [HazyResearch/snorkel#1068]
I note that the GenerativeModel.marginals is called marginals, but indeed, it computes the condition distribution of P(Y|L)

**Comment by vumaasha** [comment]
The Generative model models the joint probability distribution P(X,Y), however since Y is unobserved it is a latent variable. The generative model is learnt by marginal likelihood over all possible values of Y. Then this joint distribution model is used to infer P(Y|L), which is why it’s called a marginal
