### ISSUE TITLE
Saving and Loading Generative Models Weights

### ISSUE THREAD

**Issue by mhigginslp** [HazyResearch/snorkel#1074]
I would like to understand how the amount of unlabeled data effects the generative and discriminators performance without starting training from scratch.  Can you provide guidance for this?

I know this is more difficult but I would also like to be able to add LF's incrementally and watch the resulting changes in performance.  Are there any tricks I can use to implement this?

thanks!

**Comment by bhancock8** [comment]
Good question! The generative model improves with the amount of unlabeled data, because you have increasingly more information about how the LFs overlap and conflict, and that's what the model learns from to estimate their accuracies. The discriminative model only operates over labeled data (including weakly labeled data, using the probabilistic labels produced by the generative model), but a higher quality generative model will naturally result in higher quality labels and therefore a higher quality discriminative model.

As for not retraining from scratch--the intended workflow for snorkel is indeed iterative. The generative model generally trains much faster than the discriminative model (e.g., on the order of seconds to a couple minutes, rather than potentially very large DNNs). Typically, users will iterate over their LFs, looking at their data, coming up with new LFs, assessing their quality (either on a small labeled dev set or using the results of the generative model), and then either moving on to the next LF or refining the one they just wrote.
