### ISSUE TITLE
Can I use EM for generative model?

### ISSUE THREAD

**Issue by vumaasha** [HazyResearch/snorkel#1077]
Since generative model is a Latent variable model, which marginalizes over Y, i have two questions regarding the same.
1. Can we use Expectation Maximization for learning the generative model? I see that you use gibbs sampling followed by stochastic gradient to learn the model parameters. is this already a variation of EM, i don't see that you mention about EM anywhere in the papers.
2. Can I inject my knowledge that I have about the prior on P(Y) somehow?

**Comment by fredsala** [comment]
To answer your first question,

1. Yes, you can try to use EM-style techniques to learn the generative model. The Gibbs-sampling approach is a little bit different; we use it because it comes with theoretical guarantees. There's several other approaches that can be used (see our more recent work on [Metal](https://arxiv.org/abs/1810.02840), which uses matrix completion to learn the generative model).
