### ISSUE TITLE
Running the corpus processor on csv file of unlabeled sentences

### ISSUE THREAD

**Issue by Salma-Bouzid** [HazyResearch/snorkel#1086]
I am new to Snorkel and currently going through the intro Tutorial 1. I would like to use it to write labeling functions for a CSV file containing rows of unlabeled sentences. I tried converting it into a TSV file then loading it into the CSVPathsPreprocessor and DocPreprocessor as shown in the tutorial. However, I encountered the following error: Value Error: not enough values to unpack (expected 2, got 1) when running the corpus processor: 

<img width="1027" alt="Screen Shot 2019-03-27 at 7 46 32 AM" src="https://user-images.githubusercontent.com/28934572/55055868-b713f180-5064-11e9-8103-6b7fb931b912.png">

Can you explain how to load a CSV file into Snorkel? 
Thank you ^^

**Comment by bhancock8** [comment]
It looks like the issue is that you used a TSVDocPreprocessor to try to process a TSV, so when it goes to look for a tab delimiter in each row, it never finds one.  In the same file as the TSVDocPreprocessor, there is a class called `CSVPathsPreprocessor` that you could look into using (check out the documentation for that class for details). Otherwise, for a simple one-line solution, you can copy the code for the `TSVDocPreprocessor` and just change line 80 (https://github.com/HazyResearch/snorkel/blob/b047dfb032560584752cb5952a82b90943529209/snorkel/parser/doc_preprocessors.py#L80) to split on commas instead of tabs. Note though that this could fail if any of your fields have commas in them as well.

**Comment by brahmaneya** [comment]
Did this work? Feel free to reopen the issue if it didn't
