### ISSUE TITLE
Coral on master

### ISSUE THREAD

**Issue by bmaneesh** [HazyResearch/snorkel#1098]
Hello,

Firstly, great job with the tutorials! 

I am experimenting with Snorkel and realized that the generative model in snorkel.learning does not support coral based definition. I believe it only covers the dependencies manually defined between the LFs but not through the AST analysis. I have found some PR https://github.com/HazyResearch/snorkel/pull/938 related to coral based tutorials but they are not available on the master. Is there any issue with the above PR or is it safe to work on it?

**Comment by paroma** [comment]
Thank you for feedback on the tutorial!

As a temporary workaround for Coral, you can set a type for the dependency (`SIMILAR` can work) that is picked up from AST analysis and run Snorkel. For example `deps = [(0, 1, 0)]` means LFs at indices `0` and `1` are correlated since they are `SIMILAR`.

We are planning a new release for Snorkel later this summer with a revised generative model and dependency learning model, which will directly handle the dependencies from Coral as well. 

Closing this issue for now, feel free to reopen with questions!
