### ISSUE TITLE
[Question] Deriving the Marginals From the Generative Model

### ISSUE THREAD

**Issue by lazysjb** [HazyResearch/snorkel#1107]
Hi, this is just a question.
I was wondering if someone could point me to material to understand how the marginals are calculated? From the paper, I understand how the lf_accuracies are calculated but I am a bit stuck on understanding https://github.com/HazyResearch/snorkel/blob/master/snorkel/learning/gen_learning.py#L390 to L429. I guess this is trying to calculate P(Y=1|LFs, x)?
Thank you much for the help in advance.

**Comment by ajratner** [comment]
In the conditionally independent setting (where we assume no dependency edges between the LFs), it's just a simple normalized weighted majority vote; using Bayes rule:
```
P(Y=1|L) = P(L|Y=1) P(Y=1) / P(L)
```
Then because of the cond. independence assumption, `P(L|Y=1)` factorizes into the product of the individual LF conditional probabilities `P(L_i|Y=1)`.

In the more complex setting with dependencies (and for more detail on above) see the published material at snorkel.stanford.edu!  We also have a cleaner matrix-completion style formulation (from AAAI'19 paper) that will be merged into master in v0.9, so coming this summer!, which lends itself to a simple computation using the junction tree alg (e.g. from a textbook on prob. graphical models)!  More soon on this (or see AAAI'19 paper posted online)!
