### ISSUE TITLE
Can't initialize SparkLabelAnnotator

### ISSUE THREAD

**Issue by SiewLinYap** [HazyResearch/snorkel#1301]
Thanks for developing snorkel. 
While trying to check how spark can be integrated with snorkel, run into module not found when calling SparkLabelAnnotator. Error message as attached. Would appreciate if can explain further the difference usage in models.candidate vs snorkel.models.candidate. Thanks. 

<img width="896" alt="Screenshot 2019-07-21 at 1 24 00 PM" src="https://user-images.githubusercontent.com/35646492/61587437-2043e580-abbd-11e9-9b83-bf5f22c92022.png">

**Comment by henryre** [comment]
Hi @SiewLinYap, `models.candidates` for Snark refers to this file: https://github.com/HazyResearch/snorkel/blob/master/snorkel/contrib/snark/models/candidate.py. However, the import statement uses Python 2-style relative imports which is not compatible with Python 3.7 (which you're running). tl;dr this can be fixed by changing that line to `from .models.candidate import wrap_candidate`. If you want to submit that fix upstream, happy to accept the PR!

**Comment by henryre** [comment]
On a side-note, our Spark label tooling is getting overhauled in version 0.9 which will be released in a couple weeks!

**Comment by SiewLinYap** [comment]
@henryre Thanks for your fast reply. I get the module error solved following your proposed quick fix at my end but run into another error Py4JJavaError in the next step when applying the SparkLabelAnnotator with defined LFs ==> annotator.apply(LFs, split=0). Most likely will need few more fixes instead of just the one above.

Since an enhanced version will be released soon, probably I’ll keep an eye on the next release for the improvement and fixes. Thanks for attending this issue.

**Comment by henryre** [comment]
@SiewLinYap thanks for reporting! This is likely due to version incompatibility (https://stackoverflow.com/questions/41840296/pyspark-in-ipython-notebook-raises-py4jjavaerror-when-using-count-and-first). We're upgrading the dependency stack in Snorkel v0.9 (along with the Spark applier upgrades), so I'll close this for now and you can open a new issue if you continue to have difficulties with the new release.
