### ISSUE TITLE
Special candidate extraction handler for conjunctions

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#138]
Consider the sentence fragment:

"effectiveness in **colorectal** , **ovarian** , and **pancreatic cancers** , as well as in advanced NSCLC"
or
"Hepatits A, B and C"

We would like to distribute candidates across conjunctions.

**Comment by ajratner** [comment]
Related to #280

**Comment by chrismre** [comment]
@stephenbach @ajratner also for #392, we should handle this in the new design docs... or explicitly pass. It's a feature that we will need in the next rev of the data model. One difficulty is automatically featurizing it... But this would be solved if "context ids" were allowed to be abstract, rather than forced to be grounded... a little indirection, maybe. (down the road?)
