### ISSUE TITLE
Fix warm starts

### ISSUE THREAD

**Issue by henryre** [HazyResearch/snorkel#250]

**Comment by ajratner** [comment]
@henryre this still open?  more detail?

**Comment by henryre** [comment]
Yeah. Should allow option to use LR weights learned for last regularization parameter as initialization for next regularization parameter (assuming the difference between them is sufficiently small). Two line change. Can do tomorrow.

**Comment by ajratner** [comment]
We need to make all of the learning code far simpler and more readable, so that it is easy to see what's going on, read, and debug before adding any more bells and whistles.  This is one of our top priorities right now, have had some difficulties here over weekend.  Am going to close this for now, can reopen after this refactor.  Happy to discuss on phone tmrw too
