### ISSUE TITLE
Ability to export model for use 

### ISSUE THREAD

**Issue by varun-tandon** [HazyResearch/snorkel#274]
We would like to be able to export the model once it is accurate enough and begin applying it to datasets.

**Comment by chrismre** [comment]
I totally agree we should make this easier!

Can you describe the environment that you plan to export it to? We have several backends (and there is of course full-blown deepdive). When @ajratner returns, we'll definitely discuss how to support this!

**Comment by varun-tandon** [comment]
My team and I are attempting to extract relationships between biomarkers and cancers from research papers. We hope to use our model to process PDF files using Python.

**Comment by chrismre** [comment]
That sounds like a great application.

There is a trivial method to export: You could simply take the python out of the notebook and run it (in any system that scales up or out python). The question is how to make this process easier (and potentially nicely roundtrip), etc. To export, I need to know the software infrastructure you want to run on and what other constraints there are. That is, what do you want to export to? 

Perhaps you should setup a time to talk with Alex? This is something we're interested in...

**Comment by ajratner** [comment]
I agree that this is a very cool application!  (Have you been to one of the hackathons by the way / have we met?  I don't know by github name...)

I agree with @chrismre that it would be helpful to learn more.  DDLite itself is designed so that you could do the whole PDF processing pipeline within it; and soon (see Milestones) we'll also be able to leverage DeepDive modules for handling greater scale, database connection, etc.  So I'm curious both about what system you want to export to, and specifically why running within existing frameworks would not work, so that we can figure out how to support

**Comment by varun-tandon** [comment]
I am part of the team from Dr.Parag Mallick's lab; we attended the hackathon today and talked to Jason who recommended we move from ddlite to deepdive. Thanks for your replies, we would greatly appreciate your assistance at the next hackathon.

**Comment by ajratner** [comment]
Okay I figured but didn't want to presume

I would like to hear more about this recommendation- @jason-fries were you saying to move now, or to utilize deepdive once it's connected to ddlite?

Either way see you at the next hackathon!

**Comment by ajratner** [comment]
Closing this for now; can bring up again later
