### ISSUE TITLE
Ngram Candidate Offset bug

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#309]
A sentence (fragment) is tokenized by CoreNLP as follows:
`G6PD Pisticci (class III);`  ⟶ `G6PD Pisticci -LRB- class III -RRB- ; ` 

Using a Concat object defined as such:
```
types = DictionaryMatch(label="prefixes", d=['type', 'class', 'stage', 'factor'],
                        ignore_case=True, longest_match=longest_match)
type_nums = DictionaryMatch(label="prefixes", d=['i', 'ii', 'iii', 'vi', 'v', 'vi', '1a', 'iid', 'a', 'b', 'c', 'd'],
                            ignore_case=True, longest_match=longest_match)
disease_types = Concat(dict_diseases, Concat(types,type_nums))
```
yields this match (note the extra parentheses) 
`<Ngram("(class III", id=2253938-9:1198-1207, chars=[1198,1207], words=[30,32])`

That punctuation isn't in any dictionary

**Comment by ajratner** [comment]
I'll take a look in a few min!  PR feedback woohoo!! :)

What dataset is this from?

**Comment by ajratner** [comment]
What's in the dictionary used by `dict_diseases`?

I tried to replicate, but the only thing that makes any sense to me is if `dict_diseases` is matching `-LRB-` somehow... because I tried to replicate using an empty dictionary, and can't reproduce this...

If you could direct me to your notebook on a branch I could take a look too!

**Comment by ajratner** [comment]
@jason-fries this still an issue..?  I couldn't reproduce
