### ISSUE TITLE
Dockerize snorkel!

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#321]
@netj further details here?  Feel free to reassign, just thought you could provide a bit of detail here first

**Comment by netj** [comment]
There are actually two aspects: using Docker for production and for development.

DeepDive started prototyping a few scripts for development with Docker, also used by Travis:
* https://github.com/HazyResearch/deepdive/tree/master/DockerBuild
* https://github.com/HazyResearch/deepdive/blob/master/.travis.yml
* The workflow is documented: https://github.com/HazyResearch/deepdive/blob/master/doc/developer.md#-containerized-builds-and-tests

DeepDive doesn't have a good example of Docker for production yet, but it'll be a separate Dockerfile that installs runtime dependencies (instead of build-time) and the built code.  In Snorkel's case, we'd just set up a sane Python environment, pip install all requirements.txt, then start the notebook.  Snorkel users don't have to mess with the setup, and just `docker run HazyResearch/snorkel` and jump to their browser. (Caveat: Docker is the only thing they have to install, but it requires admin rights.)

Happy to take a first stab at the latter!

**Comment by ajratner** [comment]
Closing for now
