### ISSUE TITLE
Make core objects define table schema using ORM

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#322]
Check out [SQLAlchemy](http://www.sqlalchemy.org/)

**Comment by stephenbach** [comment]
Commit d44d71 finishes the relational DB backend for Corpus, Document, and Sentence.

Features:
- examples/GeneTaggerExample_Extraction.ipynb demonstrates how to parse a corpus and work with results, either parsing a new corpus or resuming work with a previously parsed corpus
- Uses connection string specified as SNORKELDB env variable, and defaults to an SQLite database in the working directory names snorkel.db if not specified ( #320 )
- Lists such as lemmas and POSes for Sentences are stored as Postgres arrays if running on Postgres, otherwise lists are pickled and stored as blobs

TODO:
- The explicit session management is probably unnecessariy complexity to expose to novice users. Should we replace

```
session = SnorkelSession()

# Skip this step to resume working with a previously created corpus
corpus = Corpus(name='Pubmed Abstracts')
session.add(corpus)
session.commit()

corpus = session.query(Corpus).order_by(desc(Corpus.id)).one()
```

with some simple helpers like

```
corpus = new_corpus('Pubmed Abstracts")
```
and
```
corpus = resume_corpus()
```

Using the Corpus constructor directly for both purposes is not possible (AFAIK), because it's designed to make a new record, not retrieve an existing one.
- Move on to DB backing for candidates, features, Mindtagger data etc. We should discuss what the official schema for these should be, specifically which classes will be ORMed, and so on.
- Make document/corpus id a compound primary key? Right now document id is a primary key, which will make working with multiple corpora a pain.

**Comment by bhancock8** [comment]
I agree with the last bullet point for sure--I think most of our objects will need either a compound primary key or constructed UIDs. 

Eventually, I assume we'd like to intermix candidates from tables and text, so we could have duplicate "context" 

I'm running into a similar issue with Ngrams in Cells in Tables in Documents in Corpora. I'm working with toy data right now, so most id numbers are just integers counting up from 0, so there are lots of duplicates. So I give all objects a UID that's just a composition of their parents (e.g., 5-3-4:3-7 is characters 3-7 in the 4th cell, 3rd table, 5th document). But even that could be an issue since 5-3 could mean the 5th doc, 3rd table or 5th doc, 3rd sentence.

**Comment by bhancock8** [comment]
Whoops! Hit the wrong button.

**Comment by ajratner** [comment]
@stephenbach this looks awesome!  I'll comment more when it's a PR, but initial:

- Should put this into tutorial/CDR_tutorial as well (this is part 1 of the new tutorial we're transitioning to)
- I agree with making the interface simpler re:comments above, but also, at the same time I think we should make the mapping to DB even more explicit.  E.g. what is "name='Pubmed Abstracts'"- how does this map to DB / table?  Want this to be very apparent to users.  So maybe they can pass in the bd connection string (to set the env variable) through a python command?
