### ISSUE TITLE
Make sure all __ne__ implemented where __eq__ implemented

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#385]
This is absurd, but yes, is necessary...

**Comment by stephenbach** [comment]
Resolved for all classes that extend SnorkelBase by 1047a9c (and parent commits).

Now any child class must explicitly override comparison methods, otherwise they raise NotImplementedError. __hash__, __eq__, and __ne__ are mandatory, __le__, __lt__, __gt__, and __ge__ also raise NotImplementedError, but they do not need to be overrode for intended functionality. Users may optionally extend these methods.
