### ISSUE TITLE
[tables-dev] batch mode not working

### ISSUE THREAD

**Issue by kuleshov** [HazyResearch/snorkel#404]
In snorkel/parser.py in TableParser.parse:

When using batch=True, it doesn't parse things correctly. For example, it doesn't assign cells to phrases correctly, all the phrases are linked to the (0,0)-th cell in their table. The while loop at line 272 never seems to be run (cell_idx is never incremented).

I set batch=False for now.

**Comment by bhancock8** [comment]
I found the cause of the problem--a few weeks ago, Stephen/Alex were working an update where they changed char_offset to refer to the offset with respect to the local context instead of the document as a whole, and that's what's causing every cell to think that it's the first cell (with 0 offset from the document). I should have a fix for it by tomorrow morning.

**Comment by bhancock8** [comment]
Being re-introduced in OmniParser version 2, which Payal is creating.
