### ISSUE TITLE
parse_corpus crashes with 

### ISSUE THREAD

**Issue by Gijs-Koot** [HazyResearch/snorkel#434]
After trying to run the tutorial a couple of time, I must have somehow corrupted the db, the `cp.parse_corpus` crashes (after all sentences are parsed) with the following error

```
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: context.stable_id [SQL: u'INSERT INTO context (type, stable_id) VALUES (?, ?)'] [parameters: ('document', u'c9843f4e-9c43-4eca-9665-37aef78f5ea3::document:0:0')]
```

Removing the database and restarting will fix this (probably), but, it's a bit annoying because parsing the document takes a while.

**Comment by ajratner** [comment]
Hi @Gijs-Koot ,

This is just the database throwing a unique error because you're trying to re-insert the same document or sentence presumably.  We don't want to assume that if you try to insert a document/sentence/etc. with the same ID, it's the same document, because this can lead to bad (silent) issues...

Deleting all rows from the corresponding table, or creating a new db will fix this.

But it's on our list to put some nicer options here to make it easy e.g. if you know you just want to restart preprocessing.  Stay tuned and thanks for the patience!

-Alex

**Comment by ajratner** [comment]
Closed in v0.5.0

**Comment by nitya-yekkirala** [comment]
how can we insert two different contexts in two individuals rows without replacing the old context document?

**Comment by nitya-yekkirala** [comment]
![screen shot 2018-04-19 at 12 18 06 pm](https://user-images.githubusercontent.com/33887999/38975866-10381ac0-43cd-11e8-8e7d-1338b47abc65.png)
