### ISSUE TITLE
Using Snorkel with non-text-based inputs

### ISSUE THREAD

**Issue by gallamine** [HazyResearch/snorkel#446]
Reading through most of the documentation and working through the tutorials it seems Snorkel is being specifically targeted for generating labels for unstructured text. Am I wrong in wanting to use it for labeling structured text/numeric data (e.g. web logs)? If so, should I go and create a new set of classes like `Corpus -> Document -> Sentence -> Span.` or should I reuse these classes and fit my problem into that structure?

**Comment by ajratner** [comment]
Hi @gallamine ,

Snorkel is primarily focused on the problem of extracting structured data from unstructured input sources.  Currently, of different types of unstructured data, we are focused on supporting text, and next up to be merged in very soon, tables and similar "semi-structured" inputs.

The method behind Snorkel--data programming--is a much more general framework for weakly supervising models, and Snorkel also could be applied more generally, and you're right that you would go about this by creating a new context hierarchy; but I don't have a great idea of whether or not it will be worth the effort for your use case, since we mostly had the unstructured-to-structured case in mind!

Thanks,
Alex
