### ISSUE TITLE
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer 

### ISSUE THREAD

**Issue by Tsmith5151** [HazyResearch/snorkel#553]
@henryre -- encountering the following error as shown below; the failure to make a connection to CoreNLP is due to running snorkel on a distributed cluster. For preprocessing/tokenizing/tagging a corpus, is NLTK a suggested workaround here? 

```
WARNING:requests.packages.urllib3.connectionpool:Retrying 
(Retry(total=None, connect=19, read=0, redirect=None)) after connection broken
```

```
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer 
````

**Comment by henryre** [comment]
Hi @Tsmith5151. Here are a couple suggestions

* You can modify the [Snorkel CoreNLP Server setup](https://github.com/HazyResearch/snorkel/blob/master/snorkel/parser.py#L208) to connect to the parser at an arbitrary address instead of on localhost. CoreNLP documentation is [here](http://stanfordnlp.github.io/CoreNLP/corenlp-server.html).
* As you suggested, you can use NLTK. You should be able to use their [Stanford parser wrapper](http://www.nltk.org/_modules/nltk/parse/stanford.html) to replicate the behavior of [snorkel.parser.CoreNLPHandler.parse](https://github.com/HazyResearch/snorkel/blob/master/snorkel/parser.py#L232). If you end up going this route and want to commit your code, feel free to submit a PR!

**Comment by Tsmith5151** [comment]
@henryre thanks for the feedback. One other question related to this, I have a json file that has been annotated using CoreNLP -- is there a way I can import this file into the sqlite.db through snorkel?

**Comment by henryre** [comment]
Hi @Tsmith5151. The Snorkel parser loads responses from the CoreNLP server in json format [here](https://github.com/HazyResearch/snorkel/blob/master/snorkel/parser.py#L247). You can modify the `parse` method to take in the file contents as `content` rather than requesting it from the server.

**Comment by Tsmith5151** [comment]
Hi @henryre thanks, worked perfectly! One other quick question; running across the following error when training the generative model with the learning functions and estimating their accuracy.  The following error occurs when calling NumbSkull ```RuntimeError: cannot cache function 'gibbsthread':```

**Comment by henryre** [comment]
Hey @Tsmith5151, this is probably a Python 2/3 compatibility issue related to Numba. If you're able to run your pipeline using Python 2, I'd give that a try.
