### ISSUE TITLE
Parser is not working 

### ISSUE THREAD

**Issue by NurzatRakhman** [HazyResearch/snorkel#577]
Hello, 

I am trying the tutorials and faced this problem. If information is welcome!!! 

Best regards, 
Nurzat
![screen shot 2017-03-06 at 5 53 46 pm](https://cloud.githubusercontent.com/assets/7561907/23620117/25c73246-0296-11e7-9321-f8003db4a991.png)

**Comment by ajratner** [comment]
Hi Nurzat,

I'm not quite sure what's going on from the info you've provided- do you have any other info on what's going on, e.g. error messages in the terminal or anything?

Also I am confused because the image of your notebook seems to show that two cells were both executed at the same time (`In [6]`)... how was the notebook executed?

**Comment by NurzatRakhman** [comment]
Hi Alex, 

thanks for response. It seems the problem was with configuration, but working in virtual environment solved the problem.

**Comment by ajratner** [comment]
Awesome!  If you have any notes on specific issues / solutions, definitely post them here, either way glad it's resolved
