### ISSUE TITLE
Redefining candidate class raises DB error

### ISSUE THREAD

**Issue by thodrek** [HazyResearch/snorkel#655]
InvalidRequestError: Table 'BLAH' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

**Comment by ajratner** [comment]
@jason-fries @stephenbach I spent a few min on this today, but giving up for now... is annoying and wasting time.  Closest I got was adding to `snorkel.candidate` (including because code not on master yet):
```python
    # Add unique constraints to the arguments
    class_attribs['__table_args__'] = (
        UniqueConstraint(*unique_args),
        {'keep_existing' : True}
    )
```
Which works as hoped, and no more error is thrown... but then if you try to query for the class, somehow it can't find the foreign keys, i.e. somehow the class is not being properly loaded...

I'll pick up again on this later (or if anyone else wants to take a stab go for it!) but maybe this is further support for moving to a metadata table / generic Candidate class only... #676
