### ISSUE TITLE
CompileError: (in table 'feature_key', column 'name'): VARCHAR requires a length on dialect mysql?

### ISSUE THREAD

**Issue by hiber-niu** [HazyResearch/snorkel#664]
When i change sqlite to mysql, tutorials(1, 2) in intro will report this error, is this a bug?

**Comment by ajratner** [comment]
Hi @hiber-niu ,

Thanks for catching this- I am guessing this is a bug since we've only tested on sqlite and Postgres.  If you can use one of those in the meantime, perhaps that's the best course of action?  Or if you want to submit a PR extending to Mysql feel free!

Otherwise we will look into this at some point soon

Thanks,
Alex

**Comment by MattMorgis** [comment]
I may take a swing at a PR that adds MySQL support. Any tips or pointers before I dive in?

**Comment by stephenbach** [comment]
Awesome! Perhaps the simplest thing is to see if adding a specific length is valid for SQLite and Postgres? Then it would work for all 3.

Otherwise, if MySQL actually requires special handling, you could set a global variable the way we do for Postgres: https://github.com/HazyResearch/snorkel/blob/master/snorkel/models/meta.py

**Comment by hiber-niu** [comment]
That's great! Waiting for your good news! @MattMorgis
