### ISSUE TITLE
UserWarning with TextRNN

### ISSUE THREAD

**Issue by regoldman** [HazyResearch/snorkel#763]
Running into the following warning when using the TextRNN function:

> UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
>   "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

The function runs quite slow with a larger dataset. Any advice would be helpful.

**Comment by henryre** [comment]
Hi @regoldman. The call to `tf.nn.embedding_lookup` throws this because the embedding table is a combination of a fixed Tensor and a Variable. It shouldn't significantly impact performance. The long training times you're seeing are likely just a result of running an RNN over long sentences on a large dataset. You can try reducing the maximum sentence length or the embedding size.
