### ISSUE TITLE
An issue with 'c.labels' to get the labels that the LFs give to a candidate

### ISSUE THREAD

**Issue by ahmadpgh** [HazyResearch/snorkel#771]
Hello,

First off, thanks for Snorkel!

I was running your init tutorial (spouse relationship). However, in the second tutorial, Intro_Tutorial_2, I did not receive any result  (just received a blank array) for the cell, `c.labels`, in the ipynb file; just after you said "_We can easily see the labels that the LFs gave to this candidate using simple ORM-enabled syntax:_". 
I can also see that some of the other attributes do not work (e.g. `c.predictions`, `c.features`). 
Since I am following exactly all the steps of the tutorial without any modification, I was wondering if it is a bug or I have done something wrong.

Thanks,

**Comment by Capable-Boys** [comment]
It seems when one candidate is not covered by any LF (i.e. 0 is assigned in all cases), the result of `c.labels` is an empty array.
I still wondering what the results of  `c.predictions` and `c.features` should be when the candidate is covered by at least one LF. Does `c.features` have anything to do with Socratic Learning?!

Thanks,

**Comment by ajratner** [comment]
Hi @Capable-Boys,

As you point out, `c.labels` is returning an empty list because no labeling functions labeled this particular candidate (note that this differs from what's in the notebook online just do to randomness in the ordering of candidates).

As for `c.predictions` and `c.features`--first of all, nice use of the ORM!  W.r.t. each:  
* The *predictions* associated with a candidate are made by the end model and thus will pertain even to candidates that were not labeled by a labeling function--and, may differ with the label given by a labeling function (in particular, the end model may "override" a labeling function that is lower accuracy, or is voting on a candidate that it pertains less too, for example). However, this particular attribute is actually deprecated and should be removed- our bad!
* The *features* associated with a candidate are independent of the labels given by the labeling functions, and just reflect certain aspects of the candidates and the surrounding context that the end model looks at.  However, in the intro tutorial, we are using an LSTM end model, which learns features on its own--thus, this attribute will be empty.

Check out the tutorials / blog posts at snorkel.stanford.edu for more (e.g. on Socratic learning), and hope this response helps!

**Comment by Capable-Boys** [comment]
Thanks for the complete answer, Alex. 

Now that I am done with the initial tutorials, I am wondering how I should proceed to the next level as I am trying to be more purposeful and specific from this point forward.

The main reason of my interest in Snorkel is to be able to utilize its great (unsupervised) power in a domain-specific task of NER, especially with the use of [IOB tagging system](url). I want to understand what the best footsteps are that I can take from here hoping at the end I'll be empowered with a system that assists me in the task of _reference recognition_ in the documents of a specific domain of interest (e.g. tourism, emergency management, legal, etc). A _reference_ refers to a document or a piece of information in that. To break it down (in a supervised scenario), considering the smallest piece of a document, let's say a word, must be tagged as a starting point of a reference (B), a word in a reference which is not a starter (I), or a word that does not belong to any reference. 

FYI, I already have some annotated data for the domains above, but as you would easily guess, they are either are not enough for supervised learning, or the context of the domain is changing in a way that some of the manual annotations will not apply to the new context.

As to using Snorkel in the tagging system above for generating automatic (weak) training data, my question here is what tutorials/papers (I almost read all of them)/weblogs would serve me better in tackling the problem above. And more importantly, based on your experience, what caveats I need to be aware of along the way!

I appreciate your reply in advance,

**Comment by ajratner** [comment]
@Capable-Boys this sounds like an awesome use case, and seems fairly well formulated!  We've done some work on NER with Snorkel although hasn't made it out into the master branch / blogs / papers just yet...

The simplest way to approach this problem is just to follow the exact same pipeline in the tutorials, except change your candidate definition & extractors to work for entities rather than relations; for example, suppose you wanted to train an NER tagger for certain types of people (rather than pairs of people), you could diff off of what's in the intro tutorial and write something like:
```
Person = candidate_subclass('Person', ['person1'])
...
cand_extractor = CandidateExtractor(Person, [ngrams], [person_matcher])
```

However, for more sophisticated approaches, perhasp @jason-fries has something to add?  Otherwise / either way stay tuned, we'll be pushing more material out on this soon!

**Comment by ajratner** [comment]
Closing for now- will be available under Q&A!
