### ISSUE TITLE
Label sentiment data

### ISSUE THREAD

**Issue by lazyprgmr** [HazyResearch/snorkel#798]
How can I use snorkel for unlabeled sentiment data(some are labeled)?

**Comment by ajratner** [comment]
Hi @lazyprgmr ,

Could you give me any more information on your setup?  Is it text?  If so, I would check out some of the tutorials for some ideas of how you might write pattern-based labeling functions and start by trying this

-Alex

**Comment by chentc** [comment]
Hi @ajratner, 

I have a similar problem. I am currently dealing with a text dataset where each sentence is tagged with some different labels. The annotation is generated by crowd workers and each sentence only has one annotation so I cannot do major vote. 

I am thinking to leverage Snorkel to write some LF so that I can generate some weak supervisions and combine them with the existing annotations, then use a generative model to get a more robust annotation. Is it possible? Thanks！

**Comment by stephenbach** [comment]
Hi @chentc,
Sounds like a great use case! After going through the [intro tutorial](https://github.com/HazyResearch/snorkel/tree/master/tutorials/intro) it should be clear. A labeling function can just return the annotation provided by the crowd worker. If you have a few workers and you want to model their accuracies individually, you can even use a separate labeling function for each worker.
