### ISSUE TITLE
BRAT annotation tool

### ISSUE THREAD

**Issue by srikar2605** [HazyResearch/snorkel#884]
Till generative model no issues, but to proceed with discriminative model we need some labelled data right? 
So, when I tried to launch BRAT, I am getting this " This site can’t be reached, localhost refused to connect."
What to do? @ajratner  @jason-fries

**Comment by jason-fries** [comment]
You do need a small set of gold annotated data to evaluate your final discriminative model. If you are doing a custom extraction task, this is where BRAT comes into play. 

For debugging, I would first test that you can install and run BRAT externally to Snorkel http://brat.nlplab.org/

**Comment by AlkaSaliss** [comment]
Hi,
I wanted to try the tutorial on BRAT_Annotation, but when I execute the import BratAnnotator, I have the following error.
Any idea where it comes from?
Thanks
![brat](https://user-images.githubusercontent.com/33458274/39622288-e2e320f8-4f91-11e8-88c9-0f770ea92f7b.png)

**Comment by stephenbach** [comment]
This typo was fixed in v0.6.3.

Of course, the syntax error is in a line of code that raises an exception, so there was also some connection issue affecting the download. I've checked and the BRAT download is currently accessible, so upgrading to 0.6.3 and trying again should help or at least provide information about the real problem.
