### ISSUE TITLE
Installing Snorkel on Windows (as a package?)

### ISSUE THREAD

**Issue by littlewine** [HazyResearch/snorkel#909]
Hello there,

first of all, very nice work, congrats!
I would like to ask if there's a way to 'properly' run Snorkel on Windows. 
In the installation instructions, I can see that you are required to run a bash script (run.sh) in order for snorkel to start. Hence, I suppose snorkel cannot really be installed inside python, only launched when working in the correct directory. 

I'm trying to run snorkel (more specifically the CDR tutorial) and I've installed cygwin to allow me run the run.sh file on Windows. I can see in the command line:
`Snorkel home directory: /cygdrive/c/Users/KrasakisA/Downloads/snorkel-master 0.6.2` 
which should be fine, however I cannot import snorkelSession or anything, unless I move the ipython notebooks into the root folder (so that os.getcwd changes to the root snorkel folder).

Is there a proper/recommended way to fix this?

Thanks in advance

**Comment by stephenbach** [comment]
Hi @littlewine,

Version 0.7, now available on master, is installable completely as a conda package. Would you let us know if it's any easier to get working on Windows? Thanks!

**Comment by littlewine** [comment]
Thanks for the update, but I have been using snorkel on Ubuntu the last couple of months.

I would be happy to try it out on Windows and give you some feedback, but I am currently too busy to do so. However, I'll let you know for sure in case I try it out.

**Comment by ajratner** [comment]
Sounds good!  Closing this for now

**Comment by snknitin** [comment]
@stephenbach There is trouble with installing the package with pip once you create a fresh env of python 3.6.8 or above. Somehow only the labeling module was missing with the rest intact. With conda install, it kept giving an error due to the torch version(I had installed pytorch 1.3 before) and said it `Collecting torch<1.2.0,>=1.1.0 (from snorkel)   Could not find a version that satisfies the requirement torch<1.2.0,>=1.1.0 (from snorkel) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2) No matching distribution found for torch<1.2.0,>=1.1.0 (from snorkel)` , but if you try the readme instructions to install the specific version of torch and then install snorkel it works. Then you simply update your torch version
