### ISSUE TITLE
Make snorkel installable as a package

### ISSUE THREAD

**Issue by dhimmel** [HazyResearch/snorkel#920]
It would be make snorkel more portable if it were installable as a package. I'm happy to try to tackle this today and tomorrow (while we're at Stanford Info Lab). The plan would be to create a `setup.py` so snorkel could be installed as a package in a versioned way. This hopefully would reduce the need to set environment variables, which has been causing us headaches.

Related content:

+ `treedlib` is now pip installable (thanks to @lukehsiao in https://github.com/HazyResearch/treedlib/pull/43)
+ here's the [conda environment](https://github.com/greenelab/snorkeling/blob/6336bc6769e8c1edae5e4368dbd0c4d4dcd3e7de/environment.yml) we're currently using which could be a good reference.
+ Refs  https://github.com/HazyResearch/snorkel/issues/909
+ Refs https://github.com/HazyResearch/snorkel/pull/918
+ Refs https://github.com/HazyResearch/snorkel/issues/505

@ajratner and @stephenbach: do you know of any reasons that prevent using snorkel as a package rather than submodule?

**Comment by lukehsiao** [comment]
@dhimmel We recently made [Fonduer](https://github.com/HazyResearch/fonduer/) pip-installable. Some other things you'll need to watch out for:

- Environment variables, basically these shouldn't need to be there at all, instead, we refactored the code to use proper paths, or have extra parameters that could specify information that was previously done in environment vars
- Making dependencies clear: for example, sqlite, corenlp, postgres, etc. The docs will need to be updated with that information.
- File organization: Right now the tutorials in this repository depend on this repo's organization. You don't want to have tutorials and other unrelated code packaged with snorkel. We recently split out our tutorials into a [separate repo](https://github.com/HazyResearch/fonduer-tutorials) in order to be a more accurate representation of how to use Fonduer as a pip package. If you don't want to split them out, you'll just need to make sure that setup.py does the right thing.

I'm sure there's more, but at least those are some things to consider.

**Comment by dhimmel** [comment]
Great thanks @lukehsiao. I've made some good progress in https://github.com/HazyResearch/snorkel/pull/921. I actually didn't see your comment above until I was deep into that PR --- otherwise I would have seen if we could have cherry picked your fonduer commits.

Anyways, are in the Info Lab at Stanford. If so, want to stop by the computer lab to chat?

**Comment by stephenbach** [comment]
Fixed in version 0.7. Thanks @dhimmel!
