### ISSUE TITLE
Result of Snorkel after Descriminative model

### ISSUE THREAD

**Issue by pidugusundeep** [HazyResearch/snorkel#935]
How do i check the result of the discriminative model for the test data in the into-3 tutorial and how do i use this LSTM model which is saved finally to get results from the new set of sentences and documents.

**Comment by stephenbach** [comment]
Hi,

Hi, thanks for trying Snorkel!

The sets tp, fp, tn, fn that come from the LSTM error analysis can be viewed in the Viewer just like in intro. tutorial 2.

You can reload the classifier in new scripts / notebooks just by instantiating a new LSTM and using the load method, e.g.,

```
from snorkel.learning.disc_models.rnn import reRNN
lstm = reRNN(seed=1701, n_threads=None)
lstm.load("reRNN-8")
```
(or whichever epoch was best according to the training method)

**Comment by gpandey19** [comment]
How can we use the lstm model for making predictions on new data ?

**Comment by stephenbach** [comment]
The simplest way to do this is run the new data through the same preprocessing pipeline (intro. tutorial 1) and make a new split of the data. (As mentioned in the tutorial, you can point the notebook to a different database to start a new corpus rather than overwrite your old one.) Then you can load the corresponding candidate set and pass it directly to the LSTM.
