### ISSUE TITLE
setup.py missing requirements

### ISSUE THREAD

**Issue by MyHumbleSelf** [HazyResearch/snorkel#985]
It seems that when you switched over to making this a proper module with setup.py, a lot of the requirements were dropped. Should probably be added back with [install_requires](https://packaging.python.org/discussions/install-requires-vs-requirements/).
```
bs4
future
futures
ipywidgets>=7.0
jupyter
lxml==3.6.4
matplotlib
nltk
numba
git+https://github.com/HazyResearch/numbskull@master
numpy>=1.11
pandas
requests
scipy>=0.18
six
sqlalchemy>=1.0.14
tensorflow>=1.0
tika
spacy==1.10.0
psycopg2
py4j
```

**Comment by stephenbach** [comment]
Thanks for pointing this out! cc @dhimmel Did they get dropped for a particular reason, or were we just thinking of a conda environment install at the time? Thoughts?

**Comment by dhimmel** [comment]
Currently the setup command does not include any `install_requires`. See

https://github.com/HazyResearch/snorkel/blob/f1712dc794711c6174018f9658227b9353904fac/setup.py#L20

> It seems that when you switched over to making this a proper module with setup.py, a lot of the requirements were dropped

The requirements are now all in [`environment.yml`](https://github.com/HazyResearch/snorkel/blob/master/environment.yml). Given the considerable number of dependencies and the danger of diverging requirement specs (one in `setup.py` and one for conda), we decided to only support conda environments. @MyHumbleSelf is there a reason you cannot use a conda environment as described in the README?

If people really need to be able to install dependencies via `pip install snorkel`, we could have `setup.py` populate `install_requires` from `environment.yml`. However, I'd have to do more research to know if this would be a viable strategy.

**Comment by MyHumbleSelf** [comment]
I hate conda for all sorts of reasons and generally use venv and pip in my local and server environment. I think people just prefer different dev setups and larger libraries generally are forced to support both. I'm not as familiar with the conda setup, but it's fairly common for libraries to have both a `setup.py` and a `requirements.txt` file where the `setup.py` file parses the requirements, so the approach you describe to parsing `environment.yml` sounds fine.

This isn't a show-stopper for us at all. Just wanted to point it out. We have a dev setup where we have our own setup script which just adds snorkel into our python paths so we can actually modify snorkel as we please and stay current with master. Then there's a CI test setup and for that one, we now use pip. I currently get around the issue by just explicitly adding all of your requirements to ours.

**Comment by rspeer** [comment]
I'm interested in experimenting with Snorkel and I'll chip in on "why not use Conda": because I already use virtualenvwrapper for everything else I do, and virtualenvwrapper and Conda fight each other. Using Conda makes it harder to access my other Python environments.

I too would like the requirements to appear in setup.py.

**Comment by stephenbach** [comment]
Thanks for the feedback. We'd definitely like to support both install methods. Having setup.py parse environment.yml sounds good to me. I'll work on that.

**Comment by stephenbach** [comment]
I can't seem to request reviews from people not in the Hazy group, but feedback on #989 is very much appreciated @MyHumbleSelf @dhimmel @rspeer

**Comment by dhimmel** [comment]
If I remember correctly, prior to https://github.com/HazyResearch/snorkel/pull/921 there were dependencies that required installation via conda. Therefore, since conda was required for some things, we felt there was little downside to switching all environment management to conda.

I don't think virtualenv is a substitute. Virtualenv is for managing python packages and does not manage dependencies that are not Python packages. This also includes the inability to manage the version of Python in use as part of the environment.

> virtualenvwrapper and Conda fight each other

This has been true in the past and conda has experienced many "growing pains", but should not be the case anymore. Just make sure the installation process does not add anything to your bash profile, and the default system python should not be changed. Also I'd suggest installing miniconda rather than anaconda, if you'd like to keep things minimalist.

> people just prefer different dev setups and larger libraries generally are forced to support both

With snorkel, the dependencies are quite technical and heavy. It's not a general python package and given limited developer time, I think it makes sense to have one method for managing the environment that will be consistent and reproducible for all users.

> We have a dev setup where we have our own setup script which just adds snorkel into our python paths so we can actually modify snorkel as we please and stay current with master. 

Hopefully, you won't have to do this anymore. You should now be able to install snorkel into a conda environment using pip, either via commit hash or in development version as explained in the repo. There is now no need (only disadvantages) to the PYTHONPATH modification approach.

Happy to answer any questions / debugging with setting up the 0.7 environment.

**Comment by MyHumbleSelf** [comment]
There are no Conda-only dependencies. When we manage the rest just fine with pip, I really don’t see the need for another package manager. It also sounds like @stephenbach already got it done, so I’ll let you suss that out. At this point, we’ve been modifying snorkel for multiple feature candidate extraction and a few other things and we’ve working off our own fork. Hopefully we’ll be able to merge most of that back in.

I’ll check out microconda again in the future — thanks for the heads up!

**Comment by dhimmel** [comment]
> When we manage the rest just fine with pip, I really don’t see the need for another package manager

Okay, I think you will run into issues eventually, but perhaps the following approach will be helpful to convert `environment.yml` to `requirements.txt`:

```python
import yaml
import requests
url = 'https://github.com/HazyResearch/snorkel/raw/master/environment.yml'
response = requests.get(url)
environment = yaml.load(response.text)
dependencies = environment['dependencies']
requirements = list()
for elem in dependencies:
    if isinstance(elem, str):
        # TODO: convert package=0.0 to package==0.0
        requirements.append(elem)
    elif isinstance(elem, dict) and 'pip' in elem:
        requirements.extend(elem['pip'])
print('\n'.join(requirements))
```

This gives me the output:

```
beautifulsoup4
future
ipywidgets>=7.0
jupyter
lxml
matplotlib
nltk
numba
numpy>=1.11
pytorch>=0.4
pandas
psycopg2
py4j
python
requests
runipy
scipy
six
spacy<2
sqlalchemy>=1.0.14
tika
git+https://github.com/HazyResearch/numbskull@master
git+https://github.com/HazyResearch/treedlib@master
```

If you save that as `requirements.txt`, then I think you should be able to run the following from inside your snorkel virtualenv:

```
pip install --requirement requirements.txt
```

Would be interested in whether this installs an environment that can pass the tests.
